language: scala
sudo: false
jdk: oraclejdk9
scala:
   - 2.11.12
   - 2.12.8
   - 2.13.0

script:
- sbt ++$TRAVIS_SCALA_VERSION test proto26:test
- if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]]; then
    sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues;
  fi
