language: scala
sudo: false
jdk: oraclejdk9
scala:
   - 2.11.12
   - 2.12.10
   - 2.13.1

script:
- sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test proto26:test
- sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues;
